stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: my-go-app

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"
    - docker save $DOCKER_IMAGE | ssh user@ubuntu-server 'docker load && docker run -d -p 8080:8080 $DOCKER_IMAGE'

